import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import { test } from "node:test"

const root = new URL("../../", import.meta.url)

async function read(path) {
  return readFile(new URL(path, root), "utf8")
}

test("protected OpenAI functions use typed envelopes and authorization helpers", async () => {
  const customerResearch = await read("netlify/functions/customer-research.ts")
  const liveGuidance = await read("netlify/functions/live-guidance.ts")
  const postCallOutputs = await read("netlify/functions/post-call-outputs.ts")
  const realtimeTranscription = await read("netlify/functions/realtime-transcription.ts")
  const speakerAttribution = await read("netlify/functions/speaker-attribution.ts")
  const accountEnrichment = await read("netlify/functions/account-enrichment.ts")
  const sharedSupabase = await read("netlify/functions/_shared/supabase.ts")

  assert.match(customerResearch, /authorizeAccount/)
  assert.match(customerResearch, /authorizeOpportunity/)
  assert.match(customerResearch, /authorizeCall/)
  assert.match(customerResearch, /dataResponse/)

  assert.match(liveGuidance, /authorizeAccount/)
  assert.match(liveGuidance, /authorizeOpportunity/)
  assert.match(liveGuidance, /authorizeCall/)
  assert.match(liveGuidance, /assertLiveGuidanceResult/)
  assert.match(liveGuidance, /accountProfile/)
  assert.match(liveGuidance, /profileNotes/)
  assert.match(liveGuidance, /account profile notes/)
  assert.match(liveGuidance, /buildAccountProfileContext/)
  assert.match(liveGuidance, /live_guidance_events/)
  assert.match(liveGuidance, /ui_mode: result\.uiMode/)
  assert.match(liveGuidance, /conversation_state: \{[\s\S]*questionLifecycle: result\.questionLifecycle,[\s\S]*parkedIntents: result\.parkedIntents/)
  assert.match(liveGuidance, /candidate_scores: result\.candidateScores/)
  assert.match(liveGuidance, /source_turn_ids: transcript\.map/)
  assert.match(liveGuidance, /guidance_latency_ms: guidanceLatencyMs/)
  assert.match(liveGuidance, /dataResponse/)

  assert.match(postCallOutputs, /authorizeCall/)
  assert.match(postCallOutputs, /assertPostCallResult/)
  assert.match(postCallOutputs, /live_guidance_events/)
  assert.match(postCallOutputs, /parkedIntents/)
  assert.match(postCallOutputs, /intentionally parked because the conversation moved on/)
  assert.match(postCallOutputs, /dataResponse/)

  assert.match(realtimeTranscription, /authorizeCall/)
  assert.match(realtimeTranscription, /callId is required/)
  assert.match(realtimeTranscription, /dataResponse/)

  assert.match(speakerAttribution, /authorizeCall/)
  assert.match(speakerAttribution, /segmentText is required/)
  assert.match(speakerAttribution, /salesframe_speaker_attribution/)
  assert.match(speakerAttribution, /dataResponse/)

  assert.match(accountEnrichment, /authorizeAccount/)
  assert.match(accountEnrichment, /getDecryptedOpenAiKey/)
  assert.match(accountEnrichment, /account_enrichment_profiles/)
  assert.match(accountEnrichment, /account_enrichment_runs/)
  assert.match(accountEnrichment, /account_enrichment_storage_missing/)
  assert.match(accountEnrichment, /Account enrichment is being prepared for this workspace/)
  assert.doesNotMatch(accountEnrichment, /Apply the latest Supabase migration/)
  assert.match(accountEnrichment, /function normalizeEmployeeCountCoreField/)
  assert.match(accountEnrichment, /Rejected for employee count because the source describes users, customers, members, or another scale metric rather than workforce headcount/)
  assert.match(accountEnrichment, /callOpenAiWebSearchJson/)
  assert.match(accountEnrichment, /dataResponse/)

  assert.match(sharedSupabase, /getEnv\("SUPABASE_SERVICE_ROLE_KEY"\)/)
  assert.match(sharedSupabase, /getSupabaseForUser\(token\)/)
  assert.match(sharedSupabase, /VITE_SUPABASE_PUBLISHABLE_KEY/)
  assert.match(sharedSupabase, /Authorization: `Bearer \$\{token\}`/)
  assert.match(sharedSupabase, /supabase: SupabaseClient<Database> = getSupabaseAdmin\(\)/)
})

test("post-call outputs run a speaker correction pass before generation", async () => {
  const postCallOutputs = await read("netlify/functions/post-call-outputs.ts")
  const migration = await read("supabase/migrations/202606270006_speaker_attribution.sql")

  assert.match(postCallOutputs, /salesframe_speaker_correction/)
  assert.match(postCallOutputs, /post_call_correction/)
  assert.match(postCallOutputs, /Customer 3/)
  assert.match(migration, /speaker_confidence/)
  assert.match(migration, /speaker_needs_review/)
  assert.match(migration, /customer_3/)
})

test("shared HTTP errors use structured codes and expected statuses", async () => {
  const http = await read("netlify/functions/_shared/http.ts")
  const functionsClient = await read("src/lib/server-functions.ts")

  assert.match(http, /class AppError/)
  assert.match(http, /code: appError\.code/)
  assert.match(http, /badRequest/)
  assert.match(http, /unauthorized/)
  assert.match(http, /forbidden/)
  assert.match(http, /notFound/)
  assert.match(http, /server_configuration_missing/)
  assert.match(http, /SalesFrame AI services are not configured for this environment\./)
  assert.match(http, /isMissingServerConfiguration/)
  assert.match(functionsClient, /async function readFunctionPayload/)
  assert.match(functionsClient, /await response\.text\(\)/)
  assert.match(functionsClient, /JSON\.parse\(text\)/)
  assert.match(functionsClient, /function getFunctionErrorMessage/)
  assert.doesNotMatch(functionsClient, /await response\.json\(\)/)
})

test("environment readiness endpoint requires an authenticated user", async () => {
  const envCheck = await read("netlify/functions/env-check.ts")

  assert.match(envCheck, /requireUser\(request\)/)
  assert.match(envCheck, /dataResponse/)
})

test("OpenAI helper supports strict structured output schemas", async () => {
  const openai = await read("netlify/functions/_shared/openai.ts")

  assert.match(openai, /type: "json_schema"/)
  assert.match(openai, /callOpenAiWebSearchJson/)
  assert.match(openai, /type: "web_search"/)
  assert.match(openai, /web_search_call\.action\.sources/)
  assert.match(openai, /schemaName/)
  assert.match(openai, /strictSchema/)
  assert.match(openai, /async function readOpenAiPayload/)
  assert.match(openai, /await response\.text\(\)/)
  assert.match(openai, /function getOpenAiErrorMessage/)
  assert.match(openai, /OPENAI_TRANSCRIPTION_MODEL/)
  assert.match(openai, /OPENAI_TRANSCRIPTION_LANGUAGE/)
  assert.match(openai, /const isRealtimeWhisper = transcriptionModel === "gpt-realtime-whisper"/)
  assert.match(openai, /OPENAI_TRANSCRIPTION_DELAY/)
  assert.match(openai, /OPENAI_TRANSCRIPTION_MIXED_DELAY/)
  assert.match(openai, /getEnv\("OPENAI_TRANSCRIPTION_DELAY", "high"\)/)
  assert.match(openai, /getEnv\("OPENAI_TRANSCRIPTION_MIXED_DELAY", "xhigh"\)/)
  assert.match(openai, /supportedRealtimeTranscriptionDelays/)
  assert.match(openai, /inputConfig\.turn_detection = null/)
  assert.match(openai, /OPENAI_TRANSCRIPTION_NOISE_REDUCTION/)
  assert.match(openai, /OPENAI_TRANSCRIPTION_VAD_THRESHOLD/)
  assert.match(openai, /type: "server_vad"/)
  assert.match(openai, /silence_duration_ms/)
  assert.match(openai, /\/v1\/realtime\/client_secrets/)
  assert.match(openai, /type: "transcription"/)
  assert.doesNotMatch(openai, /\/v1\/realtime\/transcription_sessions/)
  assert.doesNotMatch(openai, /input_audio_transcription/)
  assert.doesNotMatch(openai, /await response\.json\(\)/)
})

test("OpenAI keys are scoped to the active workspace", async () => {
  const openaiKeyFunction = await read("netlify/functions/openai-key.ts")
  const openaiKeyHelper = await read("netlify/functions/_shared/openai-key.ts")
  const realtimeTranscription = await read("netlify/functions/realtime-transcription.ts")
  const liveGuidance = await read("netlify/functions/live-guidance.ts")
  const sellerDomainResearch = await read("netlify/functions/seller-domain-research.ts")
  const functionsClient = await read("src/lib/server-functions.ts")
  const types = await read("src/lib/supabase/database.types.ts")
  const migration = await read("supabase/migrations/202606300001_workspace_scoped_ai_settings.sql")

  assert.match(openaiKeyFunction, /workspaceId is required/)
  assert.match(openaiKeyFunction, /authorizeWorkspace\(user\.id, workspaceId, supabase\)/)
  assert.match(openaiKeyHelper, /\.eq\("workspace_id", workspaceId\)/)
  assert.match(openaiKeyHelper, /onConflict: "workspace_id,user_id,provider"/)
  assert.match(realtimeTranscription, /getDecryptedOpenAiKey\(supabase, user\.id, call\.workspace_id\)/)
  assert.match(liveGuidance, /getDecryptedOpenAiKey\(supabase, user\.id, authorizedCall\.workspace_id\)/)
  assert.match(sellerDomainResearch, /workspaceId is required when using a saved OpenAI key/)
  assert.match(functionsClient, /getOpenAiKeyStatus\(workspaceId: string\)/)
  assert.match(functionsClient, /saveOpenAiKey\(apiKey: string, workspaceId: string\)/)
  assert.match(functionsClient, /deleteOpenAiKey\(workspaceId: string\)/)
  assert.match(types, /workspace_id: string/)
  assert.match(migration, /add column if not exists workspace_id/)
  assert.match(migration, /unique \(workspace_id, user_id, provider\)/)
})

test("elite live-call migration stores audio preflight and transcript reconciliation metadata", async () => {
  const migration = await read("supabase/migrations/202606280005_elite_live_call_pipeline.sql")
  const types = await read("src/lib/supabase/database.types.ts")

  assert.match(migration, /audio_preflight jsonb/)
  assert.match(migration, /audio_source_summary jsonb/)
  assert.match(migration, /guidance_readiness jsonb/)
  assert.match(migration, /openai_item_id text/)
  assert.match(migration, /openai_segment_id text/)
  assert.match(migration, /audio_source_kind text/)
  assert.match(migration, /client_turn_id text/)
  assert.match(migration, /turn_sequence integer/)
  assert.match(migration, /quality_flags jsonb/)
  assert.match(migration, /transcript_segments_call_source_openai_item_unique_idx/)
  assert.match(migration, /candidate_scores jsonb/)
  assert.match(types, /audio_preflight: Json/)
  assert.match(types, /openai_item_id: string \| null/)
  assert.match(types, /guidance_latency_ms: number \| null/)
})

test("CSV import functions authorize the active workspace and reject cross-workspace writes", async () => {
  const accountImport = await read("netlify/functions/import-accounts.ts")
  const opportunityImport = await read("netlify/functions/import-opportunities.ts")
  const csvImport = await read("src/lib/csv-import.ts")

  assert.match(accountImport, /path: "\/api\/import\/accounts"/)
  assert.match(accountImport, /requireUser\(request\)/)
  assert.match(accountImport, /workspaceId is required/)
  assert.match(accountImport, /authorizeWorkspace\(user\.id, workspaceId, supabase\)/)
  assert.match(accountImport, /\.from\("accounts"\)[\s\S]*\.eq\("workspace_id", workspaceId\)/)
  assert.match(accountImport, /workspace_id: workspaceId/)
  assert.match(accountImport, /assertAccountInWorkspace/)
  assert.match(accountImport, /\.eq\("id", row\.matchedAccountId\)[\s\S]*\.eq\("workspace_id", workspaceId\)/)
  assert.match(accountImport, /cross_workspace_account_rejected/)
  assert.doesNotMatch(accountImport, /getDecryptedOpenAiKey/)
  assert.doesNotMatch(accountImport, /openai/i)

  assert.match(opportunityImport, /path: "\/api\/import\/opportunities"/)
  assert.match(opportunityImport, /requireUser\(request\)/)
  assert.match(opportunityImport, /workspaceId is required/)
  assert.match(opportunityImport, /authorizeWorkspace\(user\.id, workspaceId, supabase\)/)
  assert.match(opportunityImport, /\.from\("accounts"\)\.select\("id,name,website,currency"\)\.eq\("workspace_id", workspaceId\)/)
  assert.match(opportunityImport, /\.from\("opportunities"\)\.select\("id,name,account_id"\)\.eq\("workspace_id", workspaceId\)/)
  assert.match(opportunityImport, /workspace_id: workspaceId/)
  assert.match(opportunityImport, /assertOpportunityInWorkspace/)
  assert.match(opportunityImport, /\.eq\("id", row\.matchedOpportunityId\)[\s\S]*\.eq\("workspace_id", workspaceId\)/)
  assert.match(opportunityImport, /cross_workspace_opportunity_rejected/)
  assert.match(opportunityImport, /replaceOpportunityPlaybooks/)
  assert.match(opportunityImport, /callPlaybookAliases/)
  assert.match(opportunityImport, /canonicalPlaybook/)
  assert.doesNotMatch(opportunityImport, /getDecryptedOpenAiKey/)
  assert.doesNotMatch(opportunityImport, /openai/i)

  assert.match(csvImport, /maxFileSizeBytes: 5 \* 1024 \* 1024/)
  assert.match(csvImport, /maxRows: 5000/)
  assert.match(csvImport, /reviewPageSize: 25/)
  assert.match(csvImport, /Account name is required\./)
  assert.match(csvImport, /Opportunity name is required\./)
  assert.match(csvImport, /Account name is required to import opportunities\./)
  assert.match(csvImport, /account website\/domain/)
  assert.match(csvImport, /const action: CsvImportAction = hasErrors \|\| duplicateKind !== "none" \? "skip" : "create"/)
  assert.match(csvImport, /Close date could not be parsed; it will be saved as a note\./)
  assert.match(csvImport, /Currency "\$\{values\.currency\}" is not supported; \$\{defaultCurrency\} will be used\./)
  assert.match(csvImport, /normalizeCsvImportPlaybooks/)
})
